## NumPy

Manipulando arrays

In [2]:
import numpy as np

### Fatiar

In [4]:
ar = np.array([20,30,10,40])
print(ar[1:3])
print(ar[::2]) # não especificado início, nem fim, somento o passo

[30 10]
[20 10]


### copy()

In [5]:
ar2 = ar[:]
ar2[0] = 1000 # essa alteração irá refletir em `ar`

print(ar) 
print(ar2)

[1000   30   10   40]
[1000   30   10   40]


In [7]:
# Utilizar o comando copy() para evitar isso

ar3 = ar.copy()
ar3[0] = 2000

print(ar) 
print(ar3)

[1000   30   10   40]
[2000   30   10   40]


### insert()

In [14]:
arr = np.array([1,2,3])
np.insert(arr, 1,10) # insere valor 10 na segunda posição (1)

array([ 1, 10,  2,  3])

In [29]:
vals = np.array([[1,2,3],[3,4,5], [3,4,5]])
print(vals)
print(vals.ndim) # número de dimensões. Como é uma matriz, o valor será 2.

[[1 2 3]
 [3 4 5]
 [3 4 5]]
2


As funções que tem o parâmetro `axis` (eixo) vão funcionar nas matrizes, e não nos vetores, pois estes são unidimensionais, ou seja, possuem apenas um eixo.

* `axis=0`, eixo vertical
* `axis=1`, eixo horizontal

In [33]:
np.insert(vals, 1,100, axis=0) # insere o valor 100, na posição 1 de todas as colunas

array([[  1,   2,   3],
       [100, 100, 100],
       [  3,   4,   5],
       [  3,   4,   5]])

In [32]:
np.insert(vals, 1,100, axis=1)  # insere o valor 100, na posição 1 de todas as linhas

array([[  1, 100,   2,   3],
       [  3, 100,   4,   5],
       [  3, 100,   4,   5]])

In [26]:
vetor = np.array([6,7,8])
print(vetor)
print(vetor.ndim) # número de dimensões é 1, porque é um vetor.

[6 7 8]
1


**Exemplo com sum()**

In [38]:
"""
[1,2,3]
[3,4,5]
[3,4,5]
"""

print('Soma no eixo vertical = ', vals.sum(axis=0)) # eixo vertical (1 + 3 + 3) = 7, etc...
print('Soma no eixo horizontal = ', vals.sum(axis=1)) # eixo horizontal (1 + 2 + 3) = 6, etc...

Soma no eixo vertical =  [ 7 10 13]
Soma no eixo horizontal =  [ 6 12 12]


### append()

In [39]:
ap = np.array([100,200,300])
np.append(ap, [400,500,600])

array([100, 200, 300, 400, 500, 600])

In [41]:
ap2 = np.array([[100,200], [300,400]])
np.append(ap2, [[500,600]])

array([100, 200, 300, 400, 500, 600])

In [42]:
np.append(ap2, [[700,800]], axis=0)

array([[100, 200],
       [300, 400],
       [700, 800]])

In [50]:
# vai retornar o seguinte erro: ValueError: all the input arrays must have same number of dimensions
np.append(ap2, [700,800,900], axis=1)

### delete()

In [52]:
ard = np.array([[100,200], [300,400], [500,600]])
print(ard)

[[100 200]
 [300 400]
 [500 600]]


In [53]:
# Vamos excluir a segunda linha (posicao 1, eixo 0)
np.delete(ard, 1, 0)

array([[100, 200],
       [500, 600]])

In [54]:
# Vamos excluir a primeira linha (posicao 0, eixo 1)
np.delete(ard, 0, 1)

array([[200],
       [400],
       [600]])

In [56]:
# Exclui os valores passo 2 linhas, começando pela primeira
ard2 = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12], [13,14,15]])
np.delete(ard2, np.s_[1::2],0)

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15]])

### repeat()
Repete valores. Em uma matriz, pode ser escolhido o eixo a ser repetido.

In [57]:
d = np.array([100,200,300])
np.repeat(d, 2)

array([100, 100, 200, 200, 300, 300])

In [58]:
e = np.array([[100,200],[1,2]])
np.repeat(d, 3)

array([100, 100, 100, 200, 200, 200, 300, 300, 300])

In [60]:
np.repeat(e, 2, axis=0)

array([[100, 200],
       [100, 200],
       [  1,   2],
       [  1,   2]])

In [61]:
np.repeat(e, 2, axis=1)

array([[100, 100, 200, 200],
       [  1,   1,   2,   2]])

### tile()

Constrói um array repetindo x número de vezes

In [3]:
a = np.array([1,2,3])
np.tile(a,2)

array([1, 2, 3, 1, 2, 3])

In [4]:
b = np.array([[1,2],[1,2]])
np.tile(b,2)

array([[1, 2, 1, 2],
       [1, 2, 1, 2]])

### split()
Dividir arrays

In [6]:
c = np.array([[1,2,3],[1,2,3]])
np.array_split(c,2, axis=0)

[array([[1, 2, 3]]), array([[1, 2, 3]])]

In [7]:
c = np.array([[1,2,3],[1,2,3]])
np.array_split(c,2, axis=1)

[array([[1, 2],
        [1, 2]]), array([[3],
        [3]])]

### concatenate()

In [74]:
e = np.array([[1,2], [3,4]])
f = np.array([7,8])
g = np.array([[7,8]])
print(e, '\n')
print(f)

[[1 2]
 [3 4]] 

[7 8]


In [68]:
# Isso vai dar o seguinte erro 'all the input arrays must have same number of dimensions', 
# ou seja, os arrays precisam ter a mesma dimensão
# np.concatenate((e,f), axis=0) # Concatenar no eixo vertical

In [75]:
np.concatenate((e,g), axis=0) # Concatenar no eixo vertical

array([[1, 2],
       [3, 4],
       [7, 8]])

In [76]:
"""
Também vai dar erro, porque a concatenação é no eixo horizontal

e (2x2) =
[1, 2],
[3, 4]

g (1x1) = 
[7, 8]

e + g =
[1, 2][7, 8]
[3, 4]

Teríamos uma matriz inválida. Então, para corrigir, o ideal seria fazer a transposta de g.

e + g.T =
[1, 2][7],
[3, 4][8]

"""
np.concatenate((e,g), axis=1) # Concatenar no eixo horizontal

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [78]:
g.T

array([[7],
       [8]])

In [77]:
np.concatenate((e,g.T), axis=1)

array([[1, 2, 7],
       [3, 4, 8]])

### shuffle()

In [89]:
ordem = np.arange(100)
print(ordem)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [91]:
np.random.shuffle(ordem) # esse embaralhamento é inplace, ou seja, no próprio array
caos = ordem
print(caos)

[66 50 32 48 34 77 74 65  1 35 79 87 36 75  0 59 69 88 11  9 71 42 96 12
 67 61 92 21 38 49 95 81  2 97 89 25 44  6 70 30 56 13  7 99 24 29 94 14
 60 64 86 43 83 16 93 52  4 45 47 84 15 68 33 18 55 58  3 22 98 62 78 26
 73 41 85 37  5 39 46  8 23 80 28 91 20 76 90 63 57 17 53 54 27 40 51 72
 10 19 82 31]


### unique()

In [93]:
unicos = np.array([[1,2],[2,3],[3,3],[4,4],[4,5]])
np.unique(unicos)

array([1, 2, 3, 4, 5])

### genfromtxt()
Ler dados de um arquivo csv

In [97]:
dados = np.genfromtxt("data/arquivo.csv", delimiter=",", skip_header=1)
print(dados)

[[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]
 [34. 54. 23.]]
