## Matrizes
Uma matriz é uma estrutura de dados multidimensional onde os valores são organizados em linhas e colunas.

O python não tem uma estrutura própria para matrizes, mas se pode trabalhar com lista de listas.

In [4]:
# Matriz com 4 colunas e 3 linhas
mat = [[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]]
print(mat)

[[1, 4, 5, 12], [-5, 8, 9, 0], [-6, 7, 11, 19]]


In [5]:
print("mat =", mat) 
print("mat[1] =", mat[1])      # Segunda linha
print("mat[1][2] =", mat[1][2])   # Terceiro elemento da segunda linha
print("mat[0][-1] =", mat[0][-1])   # último elemento da primeira linha

mat = [[1, 4, 5, 12], [-5, 8, 9, 0], [-6, 7, 11, 19]]
mat[1] = [-5, 8, 9, 0]
mat[1][2] = 9
mat[0][-1] = 12


### Numpy

In [1]:
import numpy as np

In [6]:
a = np.array([1, 2, 3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [9]:
# mesma estrutura da matriz anterior 3x4 (3 linhas x 4 colunas)
_mat = np.array([[1,4,5,12],[-5, 8, 9, 0],[-6, 7, 11, 19]])
print(_mat)

[[ 1  4  5 12]
 [-5  8  9  0]
 [-6  7 11 19]]


In [14]:
print(_mat[1]) # Segunda linha
print(_mat[1][2]) # terceiro elemento da segunda linha
print(_mat[0][-1]) # último elemento da primeira linha

[-5  8  9  0]
9
12
